temp
OR-2000/twitter-phoenix-practice pull request #7
Opened 2020-12-28 09:36 UTC by OR-2000

2021-01-04 04:56 UTC, shunjilin commented on assets/js/api/request.js
> +      .catch(() => {
you are using an empty catch block here to handle errors, which means that errors will occur silently - this can lead to difficult to trace bugs/errors!

You can either handle the error by doing something, e.g. logging the error and rethrowing the error, or you can remove the catch block entirely to let the client's (components) handle the error instead. E.g. in app_bar.vue, I can do:

`
 try {
 await request.makeChanges(config);
 } catch (e) {
 // show some error message in the front-end
 }
`

2021-01-04 05:20 UTC, OR-2000 commented on assets/js/api/request.js
> +      .catch(() => {
ありがとうございます！

2021-01-04 05:43 UTC, shunjilin reviewed
Looks good overall!

Left some minor comments, also try to install a formatter like prettier to take care of the formatting:
https://prettier.io/docs/en/install.html

2021-01-04 05:43 UTC, shunjilin commented on assets/js/api/request.js
> +    await axios.get(url.href).then((response) => {
try to use `try/catch` with `async/await` instead of then / catch syntax unless necessary, just to keep things consistent.

async await with try catch makes asynchronous code look more like synchronous code and can help avoid too much nesting which may be hard to read:
https://www.smashingmagazine.com/2020/11/comparison-async-await-versus-then-catch/

2021-01-04 05:43 UTC, shunjilin commented on assets/tests/user_show.spec.js
> +const wrapper = shallowMount(UserShow)
It seems your test may be failing here, you may need to setup window location pathname before shallow mounting as your component is calling `fetchData()` on `created` life cycle, which is called during creation

same for tests/tweet_update.spec.js

2021-01-04 05:43 UTC, shunjilin commented on lib/twitter_phoenix_practice_web/controllers/api/like_controller.ex
> +        |> render("empty.json")
returning empty json is OK as the client app does not need to do anything with data, but if you are designing a more general API you may want to consider returning some useful information!

I think there is a book on API design on the google drive if you are interested

2021-01-04 05:43 UTC, shunjilin commented on assets/.eslintrc.js
> +      // files: [
remove if uneeded!

2021-01-04 05:43 UTC, shunjilin commented on assets/tests/app_bar.spec.js
> +  wrapper.vm.goCreateUser();
If possible, you can increase test coverage by not using the method goCreateUser directly, but by triggering a click event on the ` <button @click="goCreateUser">register</button>` component. See: https://vue-test-utils.vuejs.org/guides/getting-started.html#simulating-user-interaction
This is so that we can catch errors if the developer forgets to assign the @click handler properly 

Sometimes this may not be possible, e.g. if we are shallow mounting or if we are using a third party UI library, then we have to test the internal method directly like you do here

2021-01-09 03:44 UTC, MasashiYokota requested changes
テストまではまだ読んでいないですが、ざっと見て気になったところをコメントしました。

2021-01-09 03:44 UTC, MasashiYokota commented on assets/js/components/app_bar.vue
> +  props: ['login'],
propの型チェックを入れてください。

2021-01-09 03:44 UTC, MasashiYokota commented on assets/js/components/tweet_data.vue
> +  props: ['tweet'],
ここも型チェック入れてください。

2021-01-09 03:44 UTC, MasashiYokota commented on lib/twitter_phoenix_practice_web/controllers/api/tweet_controller.ex
> +  def show(conn, %{"id" => tweet_id}) do
型が抜けています。

2021-01-09 03:44 UTC, MasashiYokota commented on lib/twitter_phoenix_practice_web/views/api/like_view.ex
> +  end
何も返さないもの変なので、`%{message: "success"}`とかでも良いので何かしらを返してあげたほうが良いです。
他のempty.jsonも同様ですので、修正してください。

2021-01-09 04:29 UTC, OR-2000 commented on assets/js/components/app_bar.vue
> +  props: ['login'],
ありがとうございます。

2021-01-09 07:53 UTC, MasashiYokota requested changes
コメントしました！
あと、PRのタイトルとdescriptionもしっかり書きましょう！

2021-01-09 07:53 UTC, MasashiYokota commented on assets/tests/app_bar.spec.js
> +});
`describe`はネストできるので、`AppBar`のdescribeの中にこれらを書いて下さい。

2021-01-09 07:53 UTC, MasashiYokota commented on assets/tests/datas.js
> +const sampleUsers = {
ファイル名の`datas`ってのは英語として変ですね。dataはもともと複数形なので。。

2021-01-09 07:53 UTC, MasashiYokota commented on assets/tests/session_new.spec.js
> +});
ここのdescribeもネストさせて下さい。（他のコンポーネントも同様です。）

2021-01-09 08:20 UTC, MasashiYokota commented
プルリクのタイトルとプルリクの変更内容をdescriptionに書いたらLGTMです 👍

2021-01-09 08:27 UTC, OR-2000 commented
変更点：
・テストを追加
・try/catchとasync/awaitを使用
　・APIリクエスト時のエラーを出力させる

2021-01-09 08:33 UTC, merged